using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Model.Entities.Seedings;

class DocentSeeding : IEntityTypeConfiguration<Docent>
{
    public void Configure(EntityTypeBuilder<Docent> builder)
    {
        var jaar = DateTime.Today.Year;

        builder.HasData
        (
            // Toevoegen nieuwe Docent met een anonymous type
            new { DocentId = 001, Voornaam = "Willy", Familienaam = "Abbeloos", Wedde = 1400m, HeeftRijbewijs = new Nullable<bool>(), InDienst = new DateOnly(jaar, 1, 1), CampusId = 4, LandCode = "BE" },
            new { DocentId = 002, Voornaam = "Joseph", Familienaam = "Abelshausen", Wedde = 1800m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 1, 2), CampusId = 2, LandCode = "NL" },
            new { DocentId = 003, Voornaam = "Joseph", Familienaam = "Achten", Wedde = 1300m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 1, 3), CampusId = 3, LandCode = "DE" },
            new { DocentId = 004, Voornaam = "François", Familienaam = "Adam", Wedde = 1700m, HeeftRijbewijs = new Nullable<bool>(), InDienst = new DateOnly(jaar, 1, 4), CampusId = 4, LandCode = "FR" },
            new { DocentId = 005, Voornaam = "Jan", Familienaam = "Adriaensens", Wedde = 2100m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 1, 5), CampusId = 1, LandCode = "IT" },
            new { DocentId = 006, Voornaam = "René", Familienaam = "Adriaensens", Wedde = 1600m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 1, 6), CampusId = 6, LandCode = "LU" },
            new { DocentId = 007, Voornaam = "Frans", Familienaam = "Aerenhouts", Wedde = 1300m, HeeftRijbewijs = new Nullable<bool>(), InDienst = new DateOnly(jaar, 1, 7), CampusId = 3, LandCode = "BE" },
            new { DocentId = 008, Voornaam = "Emile", Familienaam = "Aerts", Wedde = 1700m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 1, 8), CampusId = 1, LandCode = "NL" },
            new { DocentId = 009, Voornaam = "Jean", Familienaam = "Aerts", Wedde = 1200m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 1, 9), CampusId = 2, LandCode = "DE" },
            new { DocentId = 010, Voornaam = "Mario", Familienaam = "Aerts", Wedde = 1600m, HeeftRijbewijs = new Nullable<bool>(), InDienst = new DateOnly(jaar, 1, 10), CampusId = 6, LandCode = "FR" },
            new { DocentId = 011, Voornaam = "Paul", Familienaam = "Aerts", Wedde = 2000m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 1, 11), CampusId = 5, LandCode = "IT" },
            new { DocentId = 012, Voornaam = "Stefan", Familienaam = "Aerts", Wedde = 1500m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 1, 12), CampusId = 5, LandCode = "LU" },
            new { DocentId = 013, Voornaam = "François", Familienaam = "Alexander", Wedde = 1900m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 1, 13), CampusId = 3, LandCode = "BE" },
            new { DocentId = 014, Voornaam = "Henri", Familienaam = "Allard", Wedde = 1600m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 1, 14), CampusId = 6, LandCode = "NL" },
            new { DocentId = 015, Voornaam = "Albert", Familienaam = "Anciaux", Wedde = 1100m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 1, 15), CampusId = 1, LandCode = "DE" },
            new { DocentId = 016, Voornaam = "Urbain", Familienaam = "Anseeuw", Wedde = 1500m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 1, 16), CampusId = 5, LandCode = "FR" },
            new { DocentId = 017, Voornaam = "Etienne", Familienaam = "Antheunis", Wedde = 1900m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 1, 17), CampusId = 3, LandCode = "IT" },
            new { DocentId = 018, Voornaam = "Jacques", Familienaam = "Arlet", Wedde = 1400m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 1, 18), CampusId = 4, LandCode = "LU" },
            new { DocentId = 019, Voornaam = "Wim", Familienaam = "Arras", Wedde = 1800m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 1, 19), CampusId = 2, LandCode = "BE" },
            new { DocentId = 020, Voornaam = "Roger", Familienaam = "Baens", Wedde = 2200m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 1, 20), CampusId = 2, LandCode = "NL" },
            new { DocentId = 021, Voornaam = "Dirk", Familienaam = "Baert", Wedde = 1000m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 1, 21), CampusId = 5, LandCode = "DE" },
            new { DocentId = 022, Voornaam = "Hubert", Familienaam = "Baert", Wedde = 1400m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 1, 22), CampusId = 4, LandCode = "FR" },
            new { DocentId = 023, Voornaam = "Jean-Pierre", Familienaam = "Baert", Wedde = 1800m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 1, 23), CampusId = 2, LandCode = "IT" },
            new { DocentId = 024, Voornaam = "Armand", Familienaam = "Baeyens", Wedde = 1300m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 1, 24), CampusId = 3, LandCode = "LU" },
            new { DocentId = 025, Voornaam = "Jan", Familienaam = "Baeyens", Wedde = 1700m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 1, 25), CampusId = 1, LandCode = "BE" },
            new { DocentId = 026, Voornaam = "Roger", Familienaam = "Baguet", Wedde = 2100m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 1, 26), CampusId = 1, LandCode = "NL" },
            new { DocentId = 027, Voornaam = "Serge", Familienaam = "Baguet", Wedde = 1600m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 1, 27), CampusId = 6, LandCode = "DE" },
            new { DocentId = 028, Voornaam = "Gérard", Familienaam = "Balducq", Wedde = 1300m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 1, 28), CampusId = 3, LandCode = "FR" },
            new { DocentId = 029, Voornaam = "Koen", Familienaam = "Barbé", Wedde = 1700m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 1, 29), CampusId = 1, LandCode = "IT" },
            new { DocentId = 030, Voornaam = "Georges", Familienaam = "Barras", Wedde = 1200m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 1, 30), CampusId = 2, LandCode = "LU" },
            new { DocentId = 031, Voornaam = "Auguste", Familienaam = "Baumans", Wedde = 1600m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 1, 31), CampusId = 6, LandCode = "BE" },
            new { DocentId = 032, Voornaam = "Arsène", Familienaam = "Bauwens", Wedde = 2000m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 2, 1), CampusId = 5, LandCode = "NL" },
            new { DocentId = 033, Voornaam = "Henri", Familienaam = "Bauwens", Wedde = 1500m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 2, 2), CampusId = 5, LandCode = "DE" },
            new { DocentId = 034, Voornaam = "Jules", Familienaam = "Bayens", Wedde = 1900m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 2, 3), CampusId = 3, LandCode = "FR" },
            new { DocentId = 035, Voornaam = "Albert", Familienaam = "Beckaert", Wedde = 1600m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 2, 4), CampusId = 6, LandCode = "IT" },
            new { DocentId = 036, Voornaam = "Marcel", Familienaam = "Beckaert", Wedde = 1100m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 2, 5), CampusId = 1, LandCode = "LU" },
            new { DocentId = 037, Voornaam = "Koen", Familienaam = "Beeckman", Wedde = 1500m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 2, 6), CampusId = 5, LandCode = "BE" },
            new { DocentId = 038, Voornaam = "Kamiel", Familienaam = "Beeckman", Wedde = 1900m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 2, 7), CampusId = 3, LandCode = "NL" },
            new { DocentId = 039, Voornaam = "Theophile", Familienaam = "Beeckman", Wedde = 1400m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 2, 8), CampusId = 4, LandCode = "DE" },
            new { DocentId = 040, Voornaam = "Benoni", Familienaam = "Beheyt", Wedde = 1800m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 2, 9), CampusId = 2, LandCode = "FR" },
            new { DocentId = 041, Voornaam = "Albert", Familienaam = "Beirnaert", Wedde = 2200m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 2, 10), CampusId = 2, LandCode = "IT" },
            new { DocentId = 042, Voornaam = "Jean", Familienaam = "Belvaux", Wedde = 1000m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 2, 11), CampusId = 5, LandCode = "LU" },
            new { DocentId = 043, Voornaam = "Adelin", Familienaam = "Benoit", Wedde = 1400m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 2, 12), CampusId = 4, LandCode = "BE" },
            new { DocentId = 044, Voornaam = "Auguste", Familienaam = "Benoit", Wedde = 1800m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 2, 13), CampusId = 2, LandCode = "NL" },
            new { DocentId = 045, Voornaam = "Jef", Familienaam = "Berben", Wedde = 1300m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 2, 14), CampusId = 3, LandCode = "DE" },
            new { DocentId = 046, Voornaam = "Jean-Pierre", Familienaam = "Berckmans", Wedde = 1700m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 2, 15), CampusId = 1, LandCode = "FR" },
            new { DocentId = 047, Voornaam = "Albert", Familienaam = "Berton", Wedde = 2100m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 2, 16), CampusId = 1, LandCode = "IT" },
            new { DocentId = 048, Voornaam = "Frans", Familienaam = "Beths", Wedde = 1600m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 2, 17), CampusId = 6, LandCode = "LU" },
            new { DocentId = 049, Voornaam = "René", Familienaam = "Beyens", Wedde = 1300m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 2, 18), CampusId = 3, LandCode = "BE" },
            new { DocentId = 050, Voornaam = "Herman", Familienaam = "Beyssens", Wedde = 1700m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 2, 19), CampusId = 1, LandCode = "NL" },
            new { DocentId = 051, Voornaam = "Albert", Familienaam = "Billiet", Wedde = 1200m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 2, 20), CampusId = 2, LandCode = "DE" },
            new { DocentId = 052, Voornaam = "Hector", Familienaam = "Billiet", Wedde = 1600m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 2, 21), CampusId = 6, LandCode = "FR" },
            new { DocentId = 053, Voornaam = "Marcel", Familienaam = "Blavier", Wedde = 2000m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 2, 22), CampusId = 5, LandCode = "IT" },
            new { DocentId = 054, Voornaam = "Roger", Familienaam = "Blockx", Wedde = 1500m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 2, 23), CampusId = 5, LandCode = "LU" },
            new { DocentId = 055, Voornaam = "Maurice", Familienaam = "Blomme", Wedde = 1900m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 2, 24), CampusId = 3, LandCode = "BE" },
            new { DocentId = 056, Voornaam = "Willy", Familienaam = "Bocklandt", Wedde = 1600m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 2, 25), CampusId = 6, LandCode = "NL" },
            new { DocentId = 057, Voornaam = "Emile", Familienaam = "Bodart", Wedde = 1100m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 2, 26), CampusId = 1, LandCode = "DE" },
            new { DocentId = 058, Voornaam = "Alfons", Familienaam = "Boekaerts", Wedde = 1500m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 2, 27), CampusId = 5, LandCode = "FR" },
            new { DocentId = 059, Voornaam = "Cesar", Familienaam = "Bogaert", Wedde = 1900m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 2, 28), CampusId = 3, LandCode = "IT" },
            new { DocentId = 060, Voornaam = "Jan", Familienaam = "Bogaert", Wedde = 1400m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 3, 1), CampusId = 4, LandCode = "LU" },
            new { DocentId = 061, Voornaam = "Jean", Familienaam = "Bogaerts", Wedde = 1800m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 3, 2), CampusId = 2, LandCode = "BE" },
            new { DocentId = 062, Voornaam = "Frans", Familienaam = "Bonduel", Wedde = 2200m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 3, 3), CampusId = 2, LandCode = "NL" },
            new { DocentId = 063, Voornaam = "Tom", Familienaam = "Boonen", Wedde = 1000m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 3, 4), CampusId = 5, LandCode = "DE" },
            new { DocentId = 064, Voornaam = "Jozef", Familienaam = "Boons", Wedde = 1400m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 3, 5), CampusId = 4, LandCode = "FR" },
            new { DocentId = 065, Voornaam = "Gabriel", Familienaam = "Borra", Wedde = 1800m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 3, 6), CampusId = 2, LandCode = "IT" },
            new { DocentId = 066, Voornaam = "Joseph", Familienaam = "Bosmans", Wedde = 1300m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 3, 7), CampusId = 3, LandCode = "LU" },
            new { DocentId = 067, Voornaam = "Walter", Familienaam = "Boucquet", Wedde = 1700m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 3, 8), CampusId = 1, LandCode = "BE" },
            new { DocentId = 068, Voornaam = "Marcel", Familienaam = "Boumon", Wedde = 2100m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 3, 9), CampusId = 1, LandCode = "NL" },
            new { DocentId = 069, Voornaam = "Ferdinand", Familienaam = "Bracke", Wedde = 1600m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 3, 10), CampusId = 6, LandCode = "DE" },
            new { DocentId = 070, Voornaam = "Adolphe", Familienaam = "Braeckeveldt", Wedde = 1300m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 3, 11), CampusId = 3, LandCode = "FR" },
            new { DocentId = 071, Voornaam = "Omer", Familienaam = "Braekevelt", Wedde = 1700m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 3, 12), CampusId = 1, LandCode = "IT" },
            new { DocentId = 072, Voornaam = "Frans", Familienaam = "Brands", Wedde = 1200m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 3, 13), CampusId = 2, LandCode = "LU" },
            new { DocentId = 073, Voornaam = "Jean", Familienaam = "Brankart", Wedde = 1600m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 3, 14), CampusId = 6, LandCode = "BE" },
            new { DocentId = 074, Voornaam = "Emile", Familienaam = "Brichard", Wedde = 2000m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 3, 15), CampusId = 5, LandCode = "NL" },
            new { DocentId = 075, Voornaam = "Georges", Familienaam = "Brosteaux", Wedde = 1500m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 3, 16), CampusId = 5, LandCode = "DE" },
            new { DocentId = 076, Voornaam = "Emile", Familienaam = "Bruneau", Wedde = 1900m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 3, 17), CampusId = 3, LandCode = "FR" },
            new { DocentId = 077, Voornaam = "Jean-Marie", Familienaam = "Bruyère", Wedde = 1600m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 3, 18), CampusId = 6, LandCode = "IT" },
            new { DocentId = 078, Voornaam = "Joseph", Familienaam = "Bruyere", Wedde = 1100m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 3, 19), CampusId = 1, LandCode = "LU" },
            new { DocentId = 079, Voornaam = "Dave", Familienaam = "Bruylandts", Wedde = 1500m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 3, 20), CampusId = 5, LandCode = "BE" },
            new { DocentId = 080, Voornaam = "Johan", Familienaam = "Bruyneel", Wedde = 1900m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 3, 21), CampusId = 3, LandCode = "NL" },
            new { DocentId = 081, Voornaam = "Lucien", Familienaam = "Buysse", Wedde = 1400m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 3, 22), CampusId = 4, LandCode = "DE" },
            new { DocentId = 082, Voornaam = "Christophe", Familienaam = "Brandt", Wedde = 1800m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 3, 23), CampusId = 2, LandCode = "FR" },
            new { DocentId = 083, Voornaam = "Norbert", Familienaam = "Callens", Wedde = 2200m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 3, 24), CampusId = 2, LandCode = "IT" },
            new { DocentId = 084, Voornaam = "Johan", Familienaam = "Capiot", Wedde = 1000m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 3, 25), CampusId = 5, LandCode = "LU" },
            new { DocentId = 085, Voornaam = "Pino", Familienaam = "Cerami", Wedde = 1400m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 3, 26), CampusId = 4, LandCode = "BE" },
            new { DocentId = 086, Voornaam = "Georges", Familienaam = "Christiaens", Wedde = 1800m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 3, 27), CampusId = 2, LandCode = "NL" },
            new { DocentId = 087, Voornaam = "Georges", Familienaam = "Claes", Wedde = 1300m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 3, 28), CampusId = 3, LandCode = "DE" },
            new { DocentId = 088, Voornaam = "Karel", Familienaam = "Clerckx", Wedde = 1700m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 3, 29), CampusId = 1, LandCode = "FR" },
            new { DocentId = 089, Voornaam = "Alex", Familienaam = "Close", Wedde = 2100m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 3, 30), CampusId = 1, LandCode = "IT" },
            new { DocentId = 090, Voornaam = "Yvan", Familienaam = "Corbusier", Wedde = 1600m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 3, 31), CampusId = 6, LandCode = "LU" },
            new { DocentId = 091, Voornaam = "Hilaire", Familienaam = "Couvreur", Wedde = 1300m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 4, 1), CampusId = 3, LandCode = "BE" },
            new { DocentId = 092, Voornaam = "Wilfried", Familienaam = "Cretskens", Wedde = 1700m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 4, 2), CampusId = 1, LandCode = "NL" },
            new { DocentId = 093, Voornaam = "Claude", Familienaam = "Criquielion", Wedde = 1200m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 4, 3), CampusId = 2, LandCode = "DE" },
            new { DocentId = 094, Voornaam = "Emile", Familienaam = "Daems", Wedde = 1600m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 4, 4), CampusId = 6, LandCode = "FR" },
            new { DocentId = 095, Voornaam = "Gustave", Familienaam = "Danneels", Wedde = 2000m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 4, 5), CampusId = 5, LandCode = "IT" },
            new { DocentId = 096, Voornaam = "Fred", Familienaam = "De Bruyne", Wedde = 1500m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 4, 6), CampusId = 5, LandCode = "LU" },
            new { DocentId = 097, Voornaam = "Arthur", Familienaam = "Decabooter", Wedde = 1900m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 4, 7), CampusId = 3, LandCode = "BE" },
            new { DocentId = 098, Voornaam = "Hans", Familienaam = "De Clerq", Wedde = 1600m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 4, 8), CampusId = 6, LandCode = "NL" },
            new { DocentId = 099, Voornaam = "Roger", Familienaam = "Decock", Wedde = 1100m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 4, 9), CampusId = 1, LandCode = "DE" },
            new { DocentId = 100, Voornaam = "Georges", Familienaam = "Decraeye", Wedde = 1500m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 4, 10), CampusId = 5, LandCode = "FR" },
            new { DocentId = 101, Voornaam = "Odiel", Familienaam = "Defraeye", Wedde = 1900m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 4, 11), CampusId = 3, LandCode = "IT" },
            new { DocentId = 102, Voornaam = "Albert", Familienaam = "De Jonghe", Wedde = 1400m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 4, 12), CampusId = 4, LandCode = "LU" },
            new { DocentId = 103, Voornaam = "Julien", Familienaam = "Delbecque", Wedde = 1800m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 4, 13), CampusId = 2, LandCode = "BE" },
            new { DocentId = 104, Voornaam = "Alfons", Familienaam = "Deloor", Wedde = 2200m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 4, 14), CampusId = 2, LandCode = "NL" },
            new { DocentId = 105, Voornaam = "Gustaaf", Familienaam = "Deloor", Wedde = 1000m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 4, 15), CampusId = 5, LandCode = "DE" },
            new { DocentId = 106, Voornaam = "Hubert", Familienaam = "Deltour", Wedde = 1400m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 4, 16), CampusId = 4, LandCode = "FR" },
            new { DocentId = 107, Voornaam = "Paul", Familienaam = "Deman", Wedde = 1800m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 4, 17), CampusId = 2, LandCode = "IT" },
            new { DocentId = 108, Voornaam = "Marc", Familienaam = "Demeyer", Wedde = 1300m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 4, 18), CampusId = 3, LandCode = "LU" },
            new { DocentId = 109, Voornaam = "Frans", Familienaam = "De Mulder", Wedde = 1700m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 4, 19), CampusId = 1, LandCode = "BE" },
            new { DocentId = 110, Voornaam = "Johan", Familienaam = "De Muynck", Wedde = 2100m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 4, 20), CampusId = 1, LandCode = "NL" },
            new { DocentId = 111, Voornaam = "Jef", Familienaam = "Demuysere", Wedde = 1600m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 4, 21), CampusId = 6, LandCode = "DE" },
            new { DocentId = 112, Voornaam = "Jules", Familienaam = "Depoorter", Wedde = 1300m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 4, 22), CampusId = 3, LandCode = "FR" },
            new { DocentId = 113, Voornaam = "Richard", Familienaam = "Depoorter", Wedde = 1700m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 4, 23), CampusId = 1, LandCode = "IT" },
            new { DocentId = 114, Voornaam = "Prosper", Familienaam = "Depredomme", Wedde = 1200m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 4, 24), CampusId = 2, LandCode = "LU" },
            new { DocentId = 115, Voornaam = "Willy", Familienaam = "Derboven", Wedde = 1600m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 4, 25), CampusId = 6, LandCode = "BE" },
            new { DocentId = 116, Voornaam = "Germain", Familienaam = "Derijcke", Wedde = 2000m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 4, 26), CampusId = 5, LandCode = "NL" },
            new { DocentId = 117, Voornaam = "Michel", Familienaam = "Dernies", Wedde = 1500m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 4, 27), CampusId = 5, LandCode = "DE" },
            new { DocentId = 118, Voornaam = "Charles", Familienaam = "Deruyter", Wedde = 1900m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 4, 28), CampusId = 3, LandCode = "FR" },
            new { DocentId = 119, Voornaam = "Maurice", Familienaam = "Desimpelaere", Wedde = 1600m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 4, 29), CampusId = 6, LandCode = "IT" },
            new { DocentId = 120, Voornaam = "Gilbert", Familienaam = "Desmet", Wedde = 1100m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 4, 30), CampusId = 1, LandCode = "LU" },
            new { DocentId = 121, Voornaam = "Georges", Familienaam = "Desplenter", Wedde = 1500m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 5, 1), CampusId = 5, LandCode = "BE" },
            new { DocentId = 122, Voornaam = "Léon", Familienaam = "Despontin", Wedde = 1900m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 5, 2), CampusId = 3, LandCode = "NL" },
            new { DocentId = 123, Voornaam = "Eric", Familienaam = "De Vlaeminck", Wedde = 1400m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 5, 3), CampusId = 4, LandCode = "DE" },
            new { DocentId = 124, Voornaam = "Roger", Familienaam = "De Vlaeminck", Wedde = 1800m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 5, 4), CampusId = 2, LandCode = "FR" },
            new { DocentId = 125, Voornaam = "Stijn", Familienaam = "Devolder", Wedde = 2200m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 5, 5), CampusId = 2, LandCode = "IT" },
            new { DocentId = 126, Voornaam = "Maurice", Familienaam = "Dewaele", Wedde = 1000m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 5, 6), CampusId = 5, LandCode = "LU" },
            new { DocentId = 127, Voornaam = "Alfons", Familienaam = "De Wolf", Wedde = 1400m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 5, 7), CampusId = 4, LandCode = "BE" },
            new { DocentId = 128, Voornaam = "Rudy", Familienaam = "Dhaenens", Wedde = 1800m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 5, 8), CampusId = 2, LandCode = "NL" },
            new { DocentId = 129, Voornaam = "Michel", Familienaam = "D''Hooghe", Wedde = 1300m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 5, 9), CampusId = 3, LandCode = "DE" },
            new { DocentId = 130, Voornaam = "Ludo", Familienaam = "Dierckxsens", Wedde = 1700m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 5, 10), CampusId = 1, LandCode = "FR" },
            new { DocentId = 131, Voornaam = "Frans", Familienaam = "Dictus", Wedde = 2100m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 5, 11), CampusId = 1, LandCode = "IT" },
            new { DocentId = 132, Voornaam = "Lomme", Familienaam = "Driessens", Wedde = 1600m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 5, 12), CampusId = 6, LandCode = "LU" },
            new { DocentId = 133, Voornaam = "Gustave", Familienaam = "Drioul", Wedde = 1300m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 5, 13), CampusId = 3, LandCode = "BE" },
            new { DocentId = 134, Voornaam = "Marcel", Familienaam = "Dupont", Wedde = 1700m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 5, 14), CampusId = 1, LandCode = "NL" },
            new { DocentId = 135, Voornaam = "Niko", Familienaam = "Eeckhout", Wedde = 1200m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 5, 15), CampusId = 2, LandCode = "DE" },
            new { DocentId = 136, Voornaam = "Nico", Familienaam = "Emonds", Wedde = 1600m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 5, 16), CampusId = 6, LandCode = "FR" },
            new { DocentId = 137, Voornaam = "Peter", Familienaam = "Farazijn", Wedde = 2000m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 5, 17), CampusId = 5, LandCode = "IT" },
            new { DocentId = 138, Voornaam = "Herman", Familienaam = "Frison", Wedde = 1500m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 5, 18), CampusId = 5, LandCode = "LU" },
            new { DocentId = 139, Voornaam = "Henri", Familienaam = "Garnier", Wedde = 1900m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 5, 19), CampusId = 3, LandCode = "BE" },
            new { DocentId = 140, Voornaam = "Frans", Familienaam = "Gielen", Wedde = 1600m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 5, 20), CampusId = 6, LandCode = "NL" },
            new { DocentId = 141, Voornaam = "Romain", Familienaam = "Gijssels", Wedde = 1100m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 5, 21), CampusId = 1, LandCode = "DE" },
            new { DocentId = 142, Voornaam = "Walter", Familienaam = "Godefroot", Wedde = 1500m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 5, 22), CampusId = 5, LandCode = "FR" },
            new { DocentId = 143, Voornaam = "Dries", Familienaam = "Govaerts", Wedde = 1900m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 5, 23), CampusId = 3, LandCode = "IT" },
            new { DocentId = 144, Voornaam = "Sylvain", Familienaam = "Grysolle", Wedde = 1400m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 5, 24), CampusId = 4, LandCode = "LU" },
            new { DocentId = 145, Voornaam = "Roger", Familienaam = "Gyselinck", Wedde = 1800m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 5, 25), CampusId = 2, LandCode = "BE" },
            new { DocentId = 146, Voornaam = "Paul", Familienaam = "Haghedooren", Wedde = 2200m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 5, 26), CampusId = 2, LandCode = "NL" },
            new { DocentId = 147, Voornaam = "Alfred", Familienaam = "Hamerlinck", Wedde = 1000m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 5, 27), CampusId = 5, LandCode = "DE" },
            new { DocentId = 148, Voornaam = "Louis", Familienaam = "Hardiquest", Wedde = 1400m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 5, 28), CampusId = 4, LandCode = "FR" },
            new { DocentId = 149, Voornaam = "Emile", Familienaam = "Hardy", Wedde = 1800m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 5, 29), CampusId = 2, LandCode = "IT" },
            new { DocentId = 150, Voornaam = "Marcel", Familienaam = "Hendrikx", Wedde = 1300m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 5, 30), CampusId = 3, LandCode = "LU" },
            new { DocentId = 151, Voornaam = "Joseph", Familienaam = "Hoevenaers", Wedde = 1700m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 5, 31), CampusId = 1, LandCode = "BE" },
            new { DocentId = 152, Voornaam = "Kevin", Familienaam = "Hulsmans", Wedde = 2100m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 6, 1), CampusId = 1, LandCode = "NL" },
            new { DocentId = 153, Voornaam = "Raymond", Familienaam = "Impanis", Wedde = 1600m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 6, 2), CampusId = 6, LandCode = "DE" },
            new { DocentId = 154, Voornaam = "Paul", Familienaam = "In''t", Wedde = 1300m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 6, 3), CampusId = 3, LandCode = "FR" },
            new { DocentId = 155, Voornaam = "Willy", Familienaam = "In''t", Wedde = 1700m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 6, 4), CampusId = 1, LandCode = "IT" },
            new { DocentId = 156, Voornaam = "Marcel", Familienaam = "Janssens", Wedde = 1200m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 6, 5), CampusId = 2, LandCode = "LU" },
            new { DocentId = 157, Voornaam = "Benjamin", Familienaam = "Javaux", Wedde = 1600m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 6, 6), CampusId = 6, LandCode = "BE" },
            new { DocentId = 158, Voornaam = "Karel", Familienaam = "Kaers", Wedde = 2000m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 6, 7), CampusId = 5, LandCode = "NL" },
            new { DocentId = 159, Voornaam = "Francis", Familienaam = "Kemplaire", Wedde = 1500m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 6, 8), CampusId = 5, LandCode = "DE" },
            new { DocentId = 160, Voornaam = "Norbert", Familienaam = "Kerckhove", Wedde = 1900m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 6, 9), CampusId = 3, LandCode = "FR" },
            new { DocentId = 161, Voornaam = "Désiré", Familienaam = "Keteleer", Wedde = 1600m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 6, 10), CampusId = 6, LandCode = "IT" },
            new { DocentId = 162, Voornaam = "Marcel", Familienaam = "Kint", Wedde = 1100m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 6, 11), CampusId = 1, LandCode = "LU" },
            new { DocentId = 163, Voornaam = "Firmin", Familienaam = "Lambot", Wedde = 1500m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 6, 12), CampusId = 5, LandCode = "BE" },
            new { DocentId = 164, Voornaam = "Roger", Familienaam = "Lambrecht", Wedde = 1900m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 6, 13), CampusId = 3, LandCode = "NL" },
            new { DocentId = 165, Voornaam = "Eric", Familienaam = "Leman", Wedde = 1400m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 6, 14), CampusId = 4, LandCode = "DE" },
            new { DocentId = 166, Voornaam = "Camille", Familienaam = "Leroy", Wedde = 1800m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 6, 15), CampusId = 2, LandCode = "FR" },
            new { DocentId = 167, Voornaam = "Roland", Familienaam = "Liboton", Wedde = 2200m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 6, 16), CampusId = 2, LandCode = "IT" },
            new { DocentId = 168, Voornaam = "Jules", Familienaam = "Lowie", Wedde = 1000m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 6, 17), CampusId = 5, LandCode = "LU" },
            new { DocentId = 169, Voornaam = "André", Familienaam = "Lurquin", Wedde = 1400m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 6, 18), CampusId = 4, LandCode = "BE" },
            new { DocentId = 170, Voornaam = "Henri", Familienaam = "Rik", Wedde = 1800m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 6, 19), CampusId = 2, LandCode = "NL" },
            new { DocentId = 171, Voornaam = "Pierrot", Familienaam = "Machiels", Wedde = 1300m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 6, 20), CampusId = 3, LandCode = "DE" },
            new { DocentId = 172, Voornaam = "André", Familienaam = "Maelbrancke", Wedde = 1700m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 6, 21), CampusId = 1, LandCode = "FR" },
            new { DocentId = 173, Voornaam = "Freddy", Familienaam = "Maertens", Wedde = 2100m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 6, 22), CampusId = 1, LandCode = "IT" },
            new { DocentId = 174, Voornaam = "Romain", Familienaam = "Maes", Wedde = 1600m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 6, 23), CampusId = 6, LandCode = "LU" },
            new { DocentId = 175, Voornaam = "Sylvère", Familienaam = "Maes", Wedde = 1300m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 6, 24), CampusId = 3, LandCode = "BE" },
            new { DocentId = 176, Voornaam = "Joseph", Familienaam = "Marchand", Wedde = 1700m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 6, 25), CampusId = 1, LandCode = "NL" },
            new { DocentId = 177, Voornaam = "René", Familienaam = "Martens", Wedde = 1200m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 6, 26), CampusId = 2, LandCode = "DE" },
            new { DocentId = 178, Voornaam = "Jacques", Familienaam = "Martin", Wedde = 1600m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 6, 27), CampusId = 6, LandCode = "FR" },
            new { DocentId = 179, Voornaam = "Emile", Familienaam = "père", Wedde = 2000m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 6, 28), CampusId = 5, LandCode = "IT" },
            new { DocentId = 180, Voornaam = "Florent", Familienaam = "Mathieu", Wedde = 1500m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 6, 29), CampusId = 5, LandCode = "LU" },
            new { DocentId = 181, Voornaam = "Nico", Familienaam = "Mattan", Wedde = 1900m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 6, 30), CampusId = 3, LandCode = "BE" },
            new { DocentId = 182, Voornaam = "Filip", Familienaam = "Meirhaeghe", Wedde = 1600m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 7, 1), CampusId = 6, LandCode = "NL" },
            new { DocentId = 183, Voornaam = "Axel", Familienaam = "Merckx", Wedde = 1100m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 7, 2), CampusId = 1, LandCode = "DE" },
            new { DocentId = 184, Voornaam = "Eddy", Familienaam = "Merckx", Wedde = 1500m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 7, 3), CampusId = 5, LandCode = "FR" },
            new { DocentId = 185, Voornaam = "André", Familienaam = "Messelis", Wedde = 1900m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 7, 4), CampusId = 3, LandCode = "IT" },
            new { DocentId = 186, Voornaam = "Maurice", Familienaam = "Meuleman", Wedde = 1400m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 7, 5), CampusId = 4, LandCode = "LU" },
            new { DocentId = 187, Voornaam = "Eloi", Familienaam = "Meulenberg", Wedde = 1800m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 7, 6), CampusId = 2, LandCode = "BE" },
            new { DocentId = 188, Voornaam = "Frans", Familienaam = "Mintjens", Wedde = 2200m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 7, 7), CampusId = 2, LandCode = "NL" },
            new { DocentId = 189, Voornaam = "Yvo", Familienaam = "Molenaers", Wedde = 1000m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 7, 8), CampusId = 5, LandCode = "DE" },
            new { DocentId = 190, Voornaam = "Maurice", Familienaam = "Mollin", Wedde = 1400m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 7, 9), CampusId = 4, LandCode = "FR" },
            new { DocentId = 191, Voornaam = "Arthur", Familienaam = "Mommerency", Wedde = 1800m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 7, 10), CampusId = 2, LandCode = "IT" },
            new { DocentId = 192, Voornaam = "Jean-Pierre", Familienaam = "Monséré", Wedde = 1300m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 7, 11), CampusId = 3, LandCode = "LU" },
            new { DocentId = 193, Voornaam = "Willy", Familienaam = "Monty", Wedde = 1700m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 7, 12), CampusId = 1, LandCode = "BE" },
            new { DocentId = 194, Voornaam = "Sammie", Familienaam = "Moreels", Wedde = 2100m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 7, 13), CampusId = 1, LandCode = "NL" },
            new { DocentId = 195, Voornaam = "Alfred", Familienaam = "Mottard", Wedde = 1600m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 7, 14), CampusId = 6, LandCode = "DE" },
            new { DocentId = 196, Voornaam = "Ernest", Familienaam = "Mottart", Wedde = 1300m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 7, 15), CampusId = 3, LandCode = "FR" },
            new { DocentId = 197, Voornaam = "Louis", Familienaam = "Mottiat", Wedde = 1700m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 7, 16), CampusId = 1, LandCode = "IT" },
            new { DocentId = 198, Voornaam = "Johan", Familienaam = "Museeuw", Wedde = 1200m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 7, 17), CampusId = 2, LandCode = "LU" },
            new { DocentId = 199, Voornaam = "Wilfried", Familienaam = "Nelissen", Wedde = 1600m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 7, 18), CampusId = 6, LandCode = "BE" },
            new { DocentId = 200, Voornaam = "François", Familienaam = "Neuville", Wedde = 2000m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 7, 19), CampusId = 5, LandCode = "NL" },
            new { DocentId = 201, Voornaam = "André", Familienaam = "Noyelle", Wedde = 1500m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 7, 20), CampusId = 5, LandCode = "DE" },
            new { DocentId = 202, Voornaam = "Guy", Familienaam = "Nulens", Wedde = 1900m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 7, 21), CampusId = 3, LandCode = "FR" },
            new { DocentId = 203, Voornaam = "Nick", Familienaam = "Nuyens", Wedde = 1600m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 7, 22), CampusId = 6, LandCode = "IT" },
            new { DocentId = 204, Voornaam = "Sven", Familienaam = "Nys", Wedde = 1100m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 7, 23), CampusId = 1, LandCode = "LU" },
            new { DocentId = 205, Voornaam = "Stan", Familienaam = "Ockers", Wedde = 1500m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 7, 24), CampusId = 5, LandCode = "BE" },
            new { DocentId = 206, Voornaam = "Petrus", Familienaam = "Oellibrandt", Wedde = 1900m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 7, 25), CampusId = 3, LandCode = "NL" },
            new { DocentId = 207, Voornaam = "Valère", Familienaam = "Ollivier", Wedde = 1400m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 7, 26), CampusId = 4, LandCode = "DE" },
            new { DocentId = 208, Voornaam = "Eddy", Familienaam = "Peelman", Wedde = 1800m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 7, 27), CampusId = 2, LandCode = "FR" },
            new { DocentId = 209, Voornaam = "Edward", Familienaam = "Peeters", Wedde = 2200m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 7, 28), CampusId = 2, LandCode = "IT" },
            new { DocentId = 210, Voornaam = "Luc", Familienaam = "Petitjean", Wedde = 1000m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 7, 29), CampusId = 5, LandCode = "LU" },
            new { DocentId = 211, Voornaam = "Victor", Familienaam = "Louis", Wedde = 1400m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 7, 30), CampusId = 4, LandCode = "BE" },
            new { DocentId = 212, Voornaam = "Georges", Familienaam = "Pintens", Wedde = 1800m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 7, 31), CampusId = 2, LandCode = "NL" },
            new { DocentId = 213, Voornaam = "Théodore", Familienaam = "Pirmez", Wedde = 1300m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 8, 1), CampusId = 3, LandCode = "DE" },
            new { DocentId = 214, Voornaam = "Eddy", Familienaam = "Planckaert", Wedde = 1700m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 8, 2), CampusId = 1, LandCode = "FR" },
            new { DocentId = 215, Voornaam = "Jo", Familienaam = "Planckaert", Wedde = 2100m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 8, 3), CampusId = 1, LandCode = "IT" },
            new { DocentId = 216, Voornaam = "Walter", Familienaam = "Planckaert", Wedde = 1600m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 8, 4), CampusId = 6, LandCode = "LU" },
            new { DocentId = 217, Voornaam = "Willy", Familienaam = "Planckaert", Wedde = 1300m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 8, 5), CampusId = 3, LandCode = "BE" },
            new { DocentId = 218, Voornaam = "Michel", Familienaam = "Pollentier", Wedde = 1700m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 8, 6), CampusId = 1, LandCode = "NL" },
            new { DocentId = 219, Voornaam = "Léon", Familienaam = "Poncelet", Wedde = 1200m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 8, 7), CampusId = 2, LandCode = "DE" },
            new { DocentId = 220, Voornaam = "Louis", Familienaam = "Proost", Wedde = 1600m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 8, 8), CampusId = 6, LandCode = "FR" },
            new { DocentId = 221, Voornaam = "Robert", Familienaam = "Protin", Wedde = 2000m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 8, 9), CampusId = 5, LandCode = "IT" },
            new { DocentId = 222, Voornaam = "Albert", Familienaam = "Ramon", Wedde = 1500m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 8, 10), CampusId = 5, LandCode = "LU" },
            new { DocentId = 223, Voornaam = "Gaston", Familienaam = "Rebry", Wedde = 1900m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 8, 11), CampusId = 3, LandCode = "BE" },
            new { DocentId = 224, Voornaam = "Jens", Familienaam = "Renders", Wedde = 1600m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 8, 12), CampusId = 6, LandCode = "NL" },
            new { DocentId = 225, Voornaam = "Guido", Familienaam = "Reybrouck", Wedde = 1100m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 8, 13), CampusId = 1, LandCode = "DE" },
            new { DocentId = 226, Voornaam = "Marcel", Familienaam = "Rijckaert", Wedde = 1500m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 8, 14), CampusId = 5, LandCode = "FR" },
            new { DocentId = 227, Voornaam = "Albert", Familienaam = "Ritserveldt", Wedde = 1900m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 8, 15), CampusId = 3, LandCode = "IT" },
            new { DocentId = 228, Voornaam = "Bert", Familienaam = "Roesems", Wedde = 1400m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 8, 16), CampusId = 4, LandCode = "LU" },
            new { DocentId = 229, Voornaam = "Louis", Familienaam = "Rolus", Wedde = 1800m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 8, 17), CampusId = 2, LandCode = "BE" },
            new { DocentId = 230, Voornaam = "Georges", Familienaam = "Ronsse", Wedde = 2200m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 8, 18), CampusId = 2, LandCode = "NL" },
            new { DocentId = 231, Voornaam = "André", Familienaam = "Rosseel", Wedde = 1000m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 8, 19), CampusId = 5, LandCode = "DE" },
            new { DocentId = 232, Voornaam = "Félicien", Familienaam = "Salmon", Wedde = 1400m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 8, 20), CampusId = 4, LandCode = "FR" },
            new { DocentId = 233, Voornaam = "Léopold", Familienaam = "Schaeken", Wedde = 1800m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 8, 21), CampusId = 2, LandCode = "IT" },
            new { DocentId = 234, Voornaam = "Willy", Familienaam = "Scheers", Wedde = 1300m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 8, 22), CampusId = 3, LandCode = "LU" },
            new { DocentId = 235, Voornaam = "Alfons", Familienaam = "Schepers", Wedde = 1700m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 8, 23), CampusId = 1, LandCode = "BE" },
            new { DocentId = 236, Voornaam = "Joseph", Familienaam = "Scherens", Wedde = 2100m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 8, 24), CampusId = 1, LandCode = "NL" },
            new { DocentId = 237, Voornaam = "Jef", Familienaam = "Scherens", Wedde = 1600m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 8, 25), CampusId = 6, LandCode = "DE" },
            new { DocentId = 238, Voornaam = "Briek", Familienaam = "Schotte", Wedde = 1300m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 8, 26), CampusId = 3, LandCode = "FR" },
            new { DocentId = 239, Voornaam = "Frans", Familienaam = "Schoubben", Wedde = 1700m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 8, 27), CampusId = 1, LandCode = "IT" },
            new { DocentId = 240, Voornaam = "Léon", Familienaam = "Scieur", Wedde = 1200m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 8, 28), CampusId = 2, LandCode = "LU" },
            new { DocentId = 241, Voornaam = "Félix", Familienaam = "Sellier", Wedde = 1600m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 8, 29), CampusId = 6, LandCode = "BE" },
            new { DocentId = 242, Voornaam = "Edward", Familienaam = "Sels", Wedde = 2000m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 8, 30), CampusId = 5, LandCode = "NL" },
            new { DocentId = 243, Voornaam = "Albert", Familienaam = "Sercu", Wedde = 1500m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 8, 31), CampusId = 5, LandCode = "DE" },
            new { DocentId = 244, Voornaam = "Patrick", Familienaam = "Sercu", Wedde = 1900m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 9, 1), CampusId = 3, LandCode = "FR" },
            new { DocentId = 245, Voornaam = "Andy", Familienaam = "de Smet", Wedde = 1600m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 9, 2), CampusId = 6, LandCode = "IT" },
            new { DocentId = 246, Voornaam = "Joseph", Familienaam = "Somers", Wedde = 1100m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 9, 3), CampusId = 1, LandCode = "LU" },
            new { DocentId = 247, Voornaam = "Tom", Familienaam = "Steels", Wedde = 1500m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 9, 4), CampusId = 5, LandCode = "BE" },
            new { DocentId = 248, Voornaam = "Ernest", Familienaam = "Sterckx", Wedde = 1900m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 9, 5), CampusId = 3, LandCode = "NL" },
            new { DocentId = 249, Voornaam = "Lucien", Familienaam = "Storme", Wedde = 1400m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 9, 6), CampusId = 4, LandCode = "DE" },
            new { DocentId = 250, Voornaam = "Tom", Familienaam = "Stubbe", Wedde = 1800m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 9, 7), CampusId = 2, LandCode = "FR" },
            new { DocentId = 251, Voornaam = "Roger", Familienaam = "Swerts", Wedde = 2200m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 9, 8), CampusId = 2, LandCode = "IT" },
            new { DocentId = 252, Voornaam = "Arthur", Familienaam = "Targez", Wedde = 1000m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 9, 10), CampusId = 5, LandCode = "LU" },
            new { DocentId = 253, Voornaam = "Andrei", Familienaam = "Tchmil", Wedde = 1400m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 9, 11), CampusId = 4, LandCode = "BE" },
            new { DocentId = 254, Voornaam = "Emmanuel", Familienaam = "Thoma", Wedde = 1800m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 9, 12), CampusId = 2, LandCode = "NL" },
            new { DocentId = 255, Voornaam = "Philippe", Familienaam = "Thys", Wedde = 1300m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 9, 13), CampusId = 3, LandCode = "DE" },
            new { DocentId = 256, Voornaam = "Hector", Familienaam = "Tiberghien", Wedde = 1700m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 9, 14), CampusId = 1, LandCode = "FR" },
            new { DocentId = 257, Voornaam = "Léon", Familienaam = "Tommies", Wedde = 2100m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 9, 15), CampusId = 1, LandCode = "IT" },
            new { DocentId = 258, Voornaam = "Lode", Familienaam = "Troonbeeckx", Wedde = 1600m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 9, 16), CampusId = 6, LandCode = "LU" },
            new { DocentId = 259, Voornaam = "Greg", Familienaam = "Van Avermaet", Wedde = 1300m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 9, 17), CampusId = 3, LandCode = "BE" },
            new { DocentId = 260, Voornaam = "Armand", Familienaam = "Van Bruaene", Wedde = 1700m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 9, 18), CampusId = 1, LandCode = "NL" },
            new { DocentId = 261, Voornaam = "Georges", Familienaam = "Vanconingsloo", Wedde = 1200m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 9, 19), CampusId = 2, LandCode = "DE" },
            new { DocentId = 262, Voornaam = "Léon", Familienaam = "Van Daele", Wedde = 1600m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 9, 20), CampusId = 6, LandCode = "FR" },
            new { DocentId = 263, Voornaam = "Charles", Familienaam = "Van Den Born", Wedde = 2000m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 9, 21), CampusId = 5, LandCode = "IT" },
            new { DocentId = 264, Voornaam = "Frank", Familienaam = "Vandenbroucke", Wedde = 1500m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 9, 22), CampusId = 5, LandCode = "LU" },
            new { DocentId = 265, Voornaam = "Odiel", Familienaam = "Vanden Meerschaut", Wedde = 1900m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 9, 23), CampusId = 3, LandCode = "BE" },
            new { DocentId = 266, Voornaam = "Eric", Familienaam = "Vanderaerden", Wedde = 1600m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 9, 24), CampusId = 6, LandCode = "NL" },
            new { DocentId = 267, Voornaam = "Kurt", Familienaam = "Van de Wouwer", Wedde = 1100m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 9, 25), CampusId = 1, LandCode = "DE" },
            new { DocentId = 268, Voornaam = "Richard", Familienaam = "Van Genechten", Wedde = 1500m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 9, 26), CampusId = 5, LandCode = "FR" },
            new { DocentId = 269, Voornaam = "Martin", Familienaam = "Van Geneugden", Wedde = 1900m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 9, 27), CampusId = 3, LandCode = "IT" },
            new { DocentId = 270, Voornaam = "Cyrille", Familienaam = "Van Hauwaert", Wedde = 1400m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 9, 28), CampusId = 4, LandCode = "LU" },
            new { DocentId = 271, Voornaam = "Maurice", Familienaam = "Van Herzele", Wedde = 1800m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 9, 30), CampusId = 2, LandCode = "BE" },
            new { DocentId = 272, Voornaam = "Jules", Familienaam = "Van Hevel", Wedde = 2200m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 10, 1), CampusId = 2, LandCode = "NL" },
            new { DocentId = 273, Voornaam = "Edwig", Familienaam = "Van Hooydonck", Wedde = 1000m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 10, 2), CampusId = 5, LandCode = "DE" },
            new { DocentId = 274, Voornaam = "Lucien", Familienaam = "Van Impe", Wedde = 1400m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 10, 3), CampusId = 4, LandCode = "FR" },
            new { DocentId = 275, Voornaam = "Henri", Familienaam = "Van Kerkhove", Wedde = 1800m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 10, 4), CampusId = 2, LandCode = "IT" },
            new { DocentId = 276, Voornaam = "Rik", Familienaam = "Van Linden", Wedde = 1300m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 10, 5), CampusId = 3, LandCode = "LU" },
            new { DocentId = 277, Voornaam = "Rik", Familienaam = "Van Looy", Wedde = 1700m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 10, 6), CampusId = 1, LandCode = "BE" },
            new { DocentId = 278, Voornaam = "Willy", Familienaam = "Vannitsen", Wedde = 2100m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 10, 7), CampusId = 1, LandCode = "NL" },
            new { DocentId = 279, Voornaam = "Peter", Familienaam = "Van Petegem", Wedde = 1600m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 10, 8), CampusId = 6, LandCode = "DE" },
            new { DocentId = 280, Voornaam = "Peter", Familienaam = "Van Santvliet", Wedde = 1300m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 10, 9), CampusId = 3, LandCode = "FR" },
            new { DocentId = 281, Voornaam = "Victor", Familienaam = "Van Schil", Wedde = 1700m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 10, 10), CampusId = 1, LandCode = "IT" },
            new { DocentId = 282, Voornaam = "Herman", Familienaam = "van Springel", Wedde = 1200m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 10, 11), CampusId = 2, LandCode = "LU" },
            new { DocentId = 283, Voornaam = "Rik", Familienaam = "Van Steenbergen", Wedde = 1600m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 10, 12), CampusId = 6, LandCode = "BE" },
            new { DocentId = 284, Voornaam = "Guillaume", Familienaam = "Van Tongerloo", Wedde = 2000m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 10, 13), CampusId = 5, LandCode = "NL" },
            new { DocentId = 285, Voornaam = "Noël", Familienaam = "Vantyghem", Wedde = 1500m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 10, 14), CampusId = 5, LandCode = "DE" },
            new { DocentId = 286, Voornaam = "Rik", Familienaam = "Verbrugghe", Wedde = 1900m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 10, 15), CampusId = 3, LandCode = "FR" },
            new { DocentId = 287, Voornaam = "Auguste", Familienaam = "Verdyck", Wedde = 1600m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 10, 16), CampusId = 6, LandCode = "IT" },
            new { DocentId = 288, Voornaam = "Jozef", Familienaam = "Verhaert", Wedde = 1100m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 10, 17), CampusId = 1, LandCode = "LU" },
            new { DocentId = 289, Voornaam = "René", Familienaam = "Vermandel", Wedde = 1500m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 10, 18), CampusId = 5, LandCode = "BE" },
            new { DocentId = 290, Voornaam = "Stive", Familienaam = "Vermaut", Wedde = 1900m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 10, 19), CampusId = 3, LandCode = "NL" },
            new { DocentId = 291, Voornaam = "Adolf", Familienaam = "Verschueren", Wedde = 1400m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 10, 20), CampusId = 4, LandCode = "DE" },
            new { DocentId = 292, Voornaam = "Constant", Familienaam = "Verschueren", Wedde = 1800m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 10, 21), CampusId = 2, LandCode = "FR" },
            new { DocentId = 293, Voornaam = "Johan", Familienaam = "Verstrepen", Wedde = 2200m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 10, 22), CampusId = 2, LandCode = "IT" },
            new { DocentId = 294, Voornaam = "Félicien", Familienaam = "Vervaecke", Wedde = 1000m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 10, 23), CampusId = 5, LandCode = "LU" },
            new { DocentId = 295, Voornaam = "Julien", Familienaam = "Vervaecke", Wedde = 1400m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 10, 24), CampusId = 4, LandCode = "BE" },
            new { DocentId = 296, Voornaam = "Edward", Familienaam = "Vissers", Wedde = 1800m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 10, 25), CampusId = 2, LandCode = "NL" },
            new { DocentId = 297, Voornaam = "Lucien", Familienaam = "Vlaemynck", Wedde = 1300m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 10, 26), CampusId = 3, LandCode = "DE" },
            new { DocentId = 298, Voornaam = "André", Familienaam = "Vlaeyen", Wedde = 1700m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 10, 27), CampusId = 1, LandCode = "FR" },
            new { DocentId = 299, Voornaam = "Jean", Familienaam = "Vliegen", Wedde = 2100m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 10, 28), CampusId = 1, LandCode = "IT" },
            new { DocentId = 300, Voornaam = "Luc", Familienaam = "Wallays", Wedde = 1600m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 10, 29), CampusId = 6, LandCode = "LU" },
            new { DocentId = 301, Voornaam = "René", Familienaam = "Walschot", Wedde = 1300m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 10, 30), CampusId = 3, LandCode = "BE" },
            new { DocentId = 302, Voornaam = "Jean-Marie", Familienaam = "Wampers", Wedde = 1700m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 10, 31), CampusId = 1, LandCode = "NL" },
            new { DocentId = 303, Voornaam = "Robert", Familienaam = "Wancour", Wedde = 1200m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 11, 1), CampusId = 2, LandCode = "DE" },
            new { DocentId = 304, Voornaam = "Bart", Familienaam = "Wellens", Wedde = 1600m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 11, 2), CampusId = 6, LandCode = "FR" },
            new { DocentId = 305, Voornaam = "Wilfried", Familienaam = "Wesemael", Wedde = 2000m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 11, 3), CampusId = 5, LandCode = "IT" },
            new { DocentId = 306, Voornaam = "Wouter", Familienaam = "Weylandt", Wedde = 1500m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 11, 4), CampusId = 5, LandCode = "LU" },
            new { DocentId = 307, Voornaam = "Marc", Familienaam = "Wauters", Wedde = 1900m, HeeftRijbewijs = false, InDienst = new DateOnly(jaar, 11, 5), CampusId = 3, LandCode = "BE" },
            new { DocentId = 308, Voornaam = "Daniel", Familienaam = "Willems", Wedde = 1600m, HeeftRijbewijs = (bool?)null, InDienst = new DateOnly(jaar, 11, 6), CampusId = 6, LandCode = "NL" },
            new { DocentId = 309, Voornaam = "Jozef", Familienaam = "Wouters", Wedde = 1100m, HeeftRijbewijs = true, InDienst = new DateOnly(jaar, 11, 7), CampusId = 1, LandCode = "DE" }
        );
    }
}
